from enum import Enum


class OutputState(Enum):
    Unknown = 'OBS_WEBSOCKET_OUTPUT_UNKNOWN'
    Starting = 'OBS_WEBSOCKET_OUTPUT_STARTING'
    Started = 'OBS_WEBSOCKET_OUTPUT_STARTED'
    Stopping = 'OBS_WEBSOCKET_OUTPUT_STOPPING'
    Stopped = 'OBS_WEBSOCKET_OUTPUT_STOPPED'
    Reconnecting = 'OBS_WEBSOCKET_OUTPUT_RECONNECTING'
    Reconnected = 'OBS_WEBSOCKET_OUTPUT_RECONNECTED'
    Paused = 'OBS_WEBSOCKET_OUTPUT_PAUSED'
    Resumed = 'OBS_WEBSOCKET_OUTPUT_RESUMED'
