name: Python application

on:
  push:
    branches: [ "main" ]
    tags:
      - "**"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
          fail-fast: false
          max-parallel: 3
          matrix:
            include:
              - os: ubuntu-24.04
                cpu: x64
              - os: windows-2022
                cpu: x64
              - os: macos-13
                cpu: x64
              - os: macos-14
                cpu: arm

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest poetry==1.8.4
        poetry install

    - name: Run tests
      run: |
        poetry run pytest

    - name: Build standalone apps
      run: |
        poetry run pyinstaller osh.spec

    - name: Collect artifcats
      run: |
        poetry run python ./ci/collect-artifacts.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: osh-${{ matrix.os }}-${{ matrix.cpu }}
        path: osh-*.zip
        if-no-files-found: error

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifact

      - name: List artifacts
        run: ls -R
        working-directory: artifact

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            artifact/**/*
          fail_on_unmatched_files: true

  # pointless job that allows using a single check for PR dependencies
  build_post:
    name: Build Post
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: "true"